### ISSUE TITLE
Niepoprawne formatowanie po implementacji szablonów 

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#1]
Po implementacji tych szablonów rozjechały się trochę divy na wysokości.

![SS](https://sc-cdn.scaleengine.net/i/8324b5fd29c4691c4b1cedbaaf755e9d.png)

**Comment by marcin-pwr** [comment]
I do that in my branch so it's waiting together with pull request. Yes it's done in html style attribute, but if we will make some other file with custom styles and add then below bootstrap.css we will easy cut and paste that. So it's no problem, and looks good now.

**Comment by ofilipowicz** [comment]
Do momentu kiedy nie poszedł merge trzymamy issue otwarte. Kiedy coś będzie już w masterze wtedy można zamykać.
