### ISSUE TITLE
Widoki profilu użytkownika

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#10]
- [x] profile-detail
- [x] profile-edit

Ench.:
- [ ] Obsługa zdjęcia
- [ ] Edycja e-maila

**Comment by marcin-pwr** [comment]
No przydałoby się zrobić, tylko co tu ma być? Profile edit to moim zdaniem np. Można dać odnośniki do tych widoków np zmiany hasła, nazwy,... No nie wiem...

**Comment by ofilipowicz** [comment]
Zrobiłem prosty widok wyświetlający i umożliwiający edycje podstawowych danych użytkownika. Teraz potrzebujemy #40. Jak starczy czasu to można zająć dodatkową funkcjonalnością, ale to zostawiam na później.

**Comment by ofilipowicz** [comment]
Na razie bez obsługi zdjęć czy zmiany maila. Zamykam.
