### ISSUE TITLE
Ostylowanie aplikacji account

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#13]
Trzeba ostylować wszystkie szablony związane z aplikacją account.

http://stackoverflow.com/questions/5827590/css-styling-in-django-forms

Będziecie musieli prawdopodobnie nadpisać formularze z gotowej paczki django-allauth. Znajdują się w waszym virtualenvie w katalogu lib/python3.4/site-packages/allauth/account/forms.py. Kopiujecie to do naszego projektu /account/forms.py i modyfikujecie. Powinno działać.

@c00perpl 
@LukeSagittarius

**Comment by ofilipowicz** [comment]
Zmieniłem trochę sposób wyświetlania formularza w szablonie [signup.html](https://github.com/ofilipowicz/owndb/blob/master/templates/account/signup.html#L21). Rozbiłem to as_p na konkretne pola, dzięki czemu macie teraz możliwość lepszej kontroli nad ostylowaniem. Dodałem też [nowy filtr](https://github.com/ofilipowicz/owndb/blob/master/store/templatetags/account_extras.py#L5) (templatetag) do store (ponieważ aplikacja account jest dla nas z definicji niedostępna). Używając tego filtra możecie w łatwy sposób dodawać klasy CSS do pól formularza. Analogicznie możecie zrobić dodawanie ID jeśli zajdzie taka potrzeba.

**Comment by marcin-pwr** [comment]
Aha, czyli ten forms.py niepotrzebny ok, no ciekawe jak to teraz wyjdzie..

**Comment by marcin-pwr** [comment]
Ciągle nie są ostylowane pola we wszystkich formularzach z apki account - zamykam bo i tak nikt tego nie zrobi. Nie spisaliście się chłopaki a issue wisiał od 2 miesięcy.
