### ISSUE TITLE
Formularze projekty - wadliwa paginacja

### ISSUE THREAD

**Issue by c00perpl** [ofilipowicz/owndb#15]
![2015-04-07-001754_1366x768_scrot](https://cloud.githubusercontent.com/assets/8625252/7013659/9a8fd798-dcbb-11e4-83f4-b47f6664adb2.png)
Nie działa mi paginacja w formularzach danej kategorii. Przycisk następna strona >> przybiera link w postaci: http://127.0.0.1:8000/store/2 zamiast prawidłowego http://127.0.0.1:8000/store/1/2/ (pasek adresu na screenie - na dole ekranu po lewej)

**Comment by ofilipowicz** [comment]
Ani jedno ani drugie nie jest poprawne. Trzeba będzie zmienić url na coś w
rodzaju /p2 jako strona druga. Inaczej występuje kolizja strony z
instancją.

**Comment by c00perpl** [comment]
Czyli ten drugi link mi działa bo działa fartem, czy jak?
![2015-04-07-003105_1366x768_scrot](https://cloud.githubusercontent.com/assets/8625252/7013862/9d59809e-dcbd-11e4-9bfd-5dc8729db871.png)

**Comment by ofilipowicz** [comment]
#16
