### ISSUE TITLE
Pole formfield.caption.

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#25]
Zostawiamy to skoro mamy możliwość dodawania labeli tekstowych? Co w przypadku kiedy ktoś nie będzie chciał nic jako nagłówek pola np. kiedy formfield.type == image? Ja bym usunął ten atrybut. Daj znać, bo bez tego nie mogę ruszyć dalej, całe wyświetlanie robiłem bez tego caption, także teraz średnio to działa i nie wiem jak to robić dalej.

@marcin-pwr

**Comment by marcin-pwr** [comment]
Tak , zostawiamy. Jeżeli nic nie będzie chciał to się dopuści możliwość zostawienia pustej nazwy. Potraktuj ten atrybut jako krótki opis pola na potrzeby wyświetlania nagłówka w tabeli instancji (jak np. na makiecie forminstances-list). W wyświetlaniu szczegółów instancji, skoro chcesz to zrobić, po prostu pomiń ten atrybut. W razie problemów zajmę się tym w piątek na zajęciach.

**Comment by ofilipowicz** [comment]
Okej. W takim razie postaram się zrobić już do końca wyświetlanie instancji.
