### ISSUE TITLE
Projekt PU Rezerwacja

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#26]
Na piątek musimy przygotować PU Rezerwacja. Przydałoby się go chyba najpierw jakoś zaprojektować, a potem dopiero przetestować w Owndb, według wcześniej stworzonego.

@c00perpl 
@marcin-pwr 
@200907 
@LukeSagittarius 
@s200894 

Ktoś się zgłasza na ochotnika?

**Comment by marcin-pwr** [comment]
Nie ma chętnych?;P może by tak bardziej to sprecyzować? Brzmi groźnie zważywszy na to co mamy i że nie mamy udostępniania formularzy jeszcze;P

**Comment by ofilipowicz** [comment]
Mamy zasymulować jakąś rezerwacje np. biletów do kina. Właściciel projektu ma w nim utworzyć kilka formularzy potrzebnych do sprecyzowania rezerwacji. Użytkownik końcowy ma otrzymać link do ?(np. pierwszego formularza) i go wypełnić. Jeśli go wypełnił ma zostać przeniesiony do kolejnego formularza i tak do końca. Jeśli wszystko jest okej to powinien otrzymać informację, że jego rezerwacja jest przetwarzana. Właściciel otrzymuje komunikat o nowej rezerwacji.

**Comment by marcin-pwr** [comment]
No niedługo powinno się to dać wyklikać...;)

**Comment by marcin-pwr** [comment]
Tylko ten mechanizm komunikatów :/ Robimy ręcznie?:P czy ten viewflow..

**Comment by marcin-pwr** [comment]
Kamil, weź w wolnej chwili napisz np.  tutaj w komentarzu co tam się udało już wyklikać, a czego brakuje i co źle działa. ten typ daty już w podstawowej wersji jest (trzeba tam by jeszcze oddzielnego pickera dodać bo na starszych przeglądarkach będzie pole tekstowe i np. możliwość ustawienia ograniczenia od jakiej do jakiej daty można wybierać), i weź właśnie napisz co i jak..

**Comment by s200894** [comment]
Narazie mam tyle co udało mi się zrobić podczas tworzenia form:
1. Podczas edycji formularza zawierającego typ connection nie udało się zatwierdzić zmian- "Some error occured while sending data. Try again later.". Podczas tworzenia nowego formularza z typem connection problemu tego nie zaobesrowałem.
2. Wyświetlanie instancji - błąd 'str' object has no attribute 'get'. Czyli po klinknięci na instancje pojawił się taki błąd. Nie wiem czy to od bazy (instancja była w bazie) czy programu, 
![blad1](https://cloud.githubusercontent.com/assets/11329148/7665473/c069ce4e-fbb8-11e4-9af1-1358e18f79e6.png)
3. Brak typu do przechowywania dat, w jakim typie przechowywać cenę z groszami? jako tekst czy liczbę?
4. Brak zagnieżdzania wyświetlania- przykład z kina:  dane filmu są w formularzu Seans, podczas wypełannia rezerwacji korzystam z connection do seans ale nie widzę danych filmu. Tak ma być?
![scr2](https://cloud.githubusercontent.com/assets/11329148/7665516/f77d65f6-fbba-11e4-9b1b-25cbccc99376.png)

**Comment by marcin-pwr** [comment]
1. Poprawione.
2. Prawdopodobnie powstała niespójność bazy po błędzie z pkt.1. (dodam większą kontrolę błędów w wolnej chwili żeby baza pozostawała spójna w momencie wystąpienia błędów w trakcie ładowania do bazy)
3. Dodałem prosty typ daty patrz uwaga wyżej^. Cenę proponuję w polu Number, z odhaczonym natural values (jednostka ew. w nazwie pola lub labelu)
4. Poprawione.

**Comment by s200894** [comment]
Dodaje sobie rzczy do bazy i mam kolejne błędy:
1. Brak ostrzeżenia, że edycja formularza może usunąć instancje !!! Pododawałem instancje, zmieniłem cośtam w formularzu i wszystkie instancje mi uciekły a nie dostałem żadnej informacji. 
2. Rozumiem że w przypadku kina formularz "Rezerwacja" będzie udostępniany użytkownikom ? Wtedy do wyboru interesującego go seansu musi wypełnić coś takiego jak na screenie ? :D to tak niebardzo bo nawet tego nie można przewijać, chyba że źle zrozumiałem jak to ma działać ?
![scr3](https://cloud.githubusercontent.com/assets/11329148/7748394/77c72a82-ffc4-11e4-90af-5dfbcc3d9bcb.png)

**Comment by marcin-pwr** [comment]
Ad1. Zrobię
Ad2. Przerzucę to do tego bootboxa i dorzucę tam autoacrolla żeby można przewijać, a tak poza tym to trzeba by zdecydować, Ew można zrobić tam linki które otwierałyby  kolejne okienka z podglądem zawartości. Albo zrobię tak, że kolumny zagnieżdżonego będą jednolicie wyświetlane na poziomie bazowych nagłówków na zerowym poziomie i będą uwzględniały widoczność która została ustalona podczas dodawania danego formularza. Bo teraz sam widzisz, że nagłówki są zdublowane w każdym polu he he. No jakby ktoś chciał wybrać to by miał rozkminkę widząc takie monstrum;)

**Comment by s200894** [comment]
Doszedłem już o co chodzi z tym udostępnaniem :p Co mi się rzuciło w oczy:
1. Po udostępnieniu formularza użytkownik powinien mieć dostęp tylko do tego formularza, bez możliwości jego edycji ani usuwania instancji.
2. Po udostępnienu użytkownik nie powinien mieć dostępu do całego projektu (np. poprzez zmianę adresu).

Poza tym coraz fajniej to zaczyna działać :)

**Comment by ofilipowicz** [comment]
Ad. 1. i 2. #45 Podpinam do tego issue, bo w sumie rozwiązanie będzie to samo.

**Comment by s200894** [comment]
Zacząłem robić drugi przypadek użycia jak Kubik chciał, czyli biblioteka. Oto co najbardziej mi przeszkadza:
1. Nie działa upload zdjęcia i pliku. Chciałem żeby książka miała zdjęcie okładki i fragment jako plik pdf.
2. Brakuje usuwania instancji.

Pytanie: Czy da się jakoś zrobić np. triggery ? Przykładowo ktoś wypełni udostępniony formularz Zamówienie i oprócz wpisu w tabeli Zamówienie pojawi się wpis w tabeli Rejestr, zawierający np. nazwę użytkownika, datę, status zamówienia ?

**Comment by marcin-pwr** [comment]
Dodałem obsługę plików (nie było jeszcze odpowiedniego modelu) oraz usuwanie instancji. Wrzucę pusha dzisiaj.

**Comment by marcin-pwr** [comment]
Heh Oskar, rozkminiłem te miniaturki jak wrzucę pusha to zerknij na rozwiązanie ;D btw, teraz działa też usuwanie plików i zdjęć;D

**Comment by ofilipowicz** [comment]
Okej, zerknę. Jeśli zaś chodzi o te triggers to aktualnie nie ma. Trzeba by
dopisać taką funkcjonalność.

**Comment by marcin-pwr** [comment]
Kamil, weź sobie spulluj mastera najlepiej na czystą bazę, potestuj i daj znać czy coś jeszcze można poprawić. Aha, nie zapomnij o tym loaddata initial_data.json ;)

**Comment by s200894** [comment]
Zrobiłem świeżutką bazę, Marcin dałem python manage.py loaddata initial_data.json ;p 

1. Pewnie to wina przegląraki (Firefox 38.0) ale jeśli w formularzu dodaję zdjęcie lub plik(pasek postępu nie ładuje się)i klikam Add instance dostaje błąd ..., jednak wpis dodaje się do bazy. 
2. Zdjęcia już działają mi bez problemu, pliki też ale jak próbuje połączyć w jednej instancji zdjęcie, plik, connection i dłuższy opis to dostaję 

DataText matching query does not exist lub File matching query does not exist.

Error during template rendering
In template /home/kamil/Pulpit/viewflow/owndb/templates/store/forminstance_list.html, error at line 57
Nie wiem czym to jest spowodowane szczerze mówiąc.

**Comment by marcin-pwr** [comment]
;D wyczuwam lekką ironię w 1 punkcie;P tak, sprawdziłem przed chwilą na tej najnowszej wersji firefoxa i wszystko działa - zatem to nie wina przeglądarki, wszystko się ładuje i zapisuje (nawet ładniej niż w chromie). Drugi błąd zapewne jest spowodowany pierwszym;) następuje utrata spójności w projekcie/formularzu. zresztą zaraz spróbuje sprawdzić.

**Comment by marcin-pwr** [comment]
Kamil pobaw się nową wersją i zrób te wszystkie przypadki użycia. Nowa wersja wymaga zmian w bazie, zmiany nie są wielkie ale najlepiej zrobić nową. Jeżeli nie chcecie nowej bazy to zróbcie migracje i twórzcie nowe projekty (nie edytujcie starych projektów ani ich zawartości bo mogły zostać śmieci które teraz spowodują błędy już naprawione w nowej wersji). Dużo poprawek doszło. Ale jak jakimś cudem wyświetli się ekran błędu to zróbcie zrzuta.

**Comment by s200894** [comment]
Jak narazie to mam taki problem, że jak zaznaczę zdjęcie do wgrania, kliknę otwórz to pasek ładowania stoi w miejscu a jak dam Add instance to pojawia sie zawsze błąd ze screena, pasek jest pełny i zdjęcie sie dodaje. Spróbuję jeszcze na Chrome
![screenshot - 04 06 2015 - 20 33 00](https://cloud.githubusercontent.com/assets/11329148/7991588/91249272-0af9-11e5-98bd-60b564d16b1f.png)

**Comment by s200894** [comment]
Na Chrome to samo :/ przy okazji: Przy tworzeniu formularza z checkboxem i zaznaczeniu kratki to ta kratka powinna być domyślnie zaznaczona przy tworzeniu instancji

**Comment by marcin-pwr** [comment]
Kamil, a więc tak:
1. Widzę masz najnowszego mastera bo masz tłumaczenie nad przyciskami;)
2. Załadowałeś fikszcersy bo byś inaczej nie dodał formularza w ogóle;)
3. U mnie wszystko działa na Chrome/Firefoxie i się dodaje zatem:
   - masz złe prawa dostępu w Linuksie dla katalogów ze zdjęciami i/lub plikami oraz CACHE'em dla miniaturek - nie można tam zapisać i masz błąd
   - w pliku local_settings.py masz złe katalogi dla MEDIA i/lub STATIC
4. Bardzo dziwne bo wcześniej Ci działało prawda? zatem co zmieniałeś?!

Dla wszystkich: trzeba zrobić ten test na serwerze docelowym żeby rozkminić deployment apki i ogólnie jakie tam problemy mogą wystąpić - wiem, że tam np. są collectstatic itp komendy oraz najważniejsze - gdzieś czytałem że apka staticfiles nie działa jak jest DEBUG=False? możliwe? no bo faktycznie jak teraz zmieniam to nie mam plików statycznych ani zdjęć ani styli - jak próbuję bezpośrednio wejść na adres ze źródła to jest 404 Not found. Pamiętam, że wcześniej przy jakiejś kombinacji ustawień mi to działało, oczywiście na stronce 404 nie było styli ale to wina względnego adresowania pewnie...
