### ISSUE TITLE
*Potrzebny lepszy tytuł*

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#27]
Pewne rzeczy i scenariusze użycia jeszcze nie są skończone w kwestii formularzy, więc z monitowaniem problemów trochę się wstrzymajcie;p

**Comment by ofilipowicz** [comment]
Jednak prośba. Dałoby radę zmienić, żeby labele nie wpisywały swojej zawartości do pola settings tylko tworzyły nową krotkę w tabeli datatext i tam dane do data, forminstance puste. Tak jak jest teraz to wytarczy, że ktoś wpisze w nazwę Plain textu "label" i problem gotowy, bo przy wyświetlaniu nie mam możliwości rozpoznać co jest labelem a co nie.

**Comment by marcin-pwr** [comment]
Zauważ, że wystarczy rozpoznawać po typie pola są przecież oddzielne LabelText, LabelImage. Jeszcze uwaga, że jeżeli "ktoś wpisze w nazwę Plain textu "label"" to nic się nie stanie, WAŻNA uwaga: zawartość atrybutu caption jeżeli typem pola jest LabelText lub LabelImage jest bez znaczenia (jest tam wpisane 'label', ale docelowo planuję to wyczyścić). Z tą możliwością to wiesz, wszystko da się zrobić kwestia tego czy koniecznie chcesz wykorzystać klasę DetailView czy zrobić to ręcznie. Zauważ, że ja już mam renderowanie formularza prawie gotowe, zatem wyrenderowanie instancji też bym mógł zrobić w tej konwencji. Drobna aczkolwiek ważna uwaga to taka, że na razie dodawanie instancji jest zrobione tylko wstępnie. Ogólnie jakoś nie widzę tego, że tak jak w poprzednim widoku co wtedy robiłeś, że w 4-5 linijkach będzie cały render instancji i w szablonie też 2-3 linijki;P...

**Comment by ofilipowicz** [comment]
Właśnie chciałem, żeby było to zrobione w tych kilku linijkach. LabelImage nie będzie przechowywał swojej informacji w settings, będzie musiał korzystać z DataImage na zasadzie jaką opisałem wcześniej (puste forminstance). Dlaczego zatem LabelText ma działać zupełnie inaczej? Jasne, mogę to ogarnąć tak jak jest teraz, ale nie widzę tu spójności.

**Comment by marcin-pwr** [comment]
Ok, to już dodane.
