### ISSUE TITLE
Błąd przy tworzeniu formularza.

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#28]
Nawet przy próbie utworzenia najprostszego (z jednym polem) formularza, dostaję [ten alert](https://github.com/ofilipowicz/owndb/blob/master/static/js/owndb-1.0.js#L290)

**Comment by ofilipowicz** [comment]
Mój błąd, zapomniałem wczytać jsona po zrobieniu nowej bazy. Teraz działa.

**Comment by marcin-pwr** [comment]
Dziwne, że samo Ci się nie wczytało. U mnie jest tak, że dzięki temu że ta nazwa jest initial_data to zasysa do bazy wraz z poleceniem migrate.

**Comment by marcin-pwr** [comment]
aha, jeszcze uwaga: tam edycja jest zrobiona na razie zresztą jak w kodzie skomentowałem tymczasowo, bo nie poprawia kluczy w skojarzonych danych, oraz nie radzę zbytnio eksperymentować jeszcze z połączeniami, bo jest w zasadzie na razie tylko 1 scenariusz kroków w których wszystko działa jak należy;P   akualnie myślę nad sposobem w jaki bedzie użytkownik używał połączenia w sensie wstawienia instancji(przedyskutujemy na zajęciach) oraz no żeby wysłać przez ajaxa zdjęcie, wkrótce powinno się udać.
