### ISSUE TITLE
Udostępnianie użytkownikom formularzy

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#29]
Przy tworzeniu/edycji formularza dodać opcję udostępniania formularza innemu użytkownikowi. (pole tekstowe na login użytkownika)

**Comment by marcin-pwr** [comment]
Tak, to by był duży plus jakby to było. Ja bym proponował to udostępnianie zrobić jakoś zbiorczo np. Dla całego projektu jeden duży widok gdzie będzie się zarządzać udostępnianiem wszystkich formularzy, byłoby wtedy fajniej niż wchodzić do każdego formularza by sprawdzić czy wszystko jest tak jak chcemy udostępnione co?

**Comment by marcin-pwr** [comment]
udostępnianie ręcznie przez wpisanie loginu, czy wybór spośród istniejących użytkowników? lub że np. najpierw dodaje się użytkownika do znajomych a potem spośród nich można udostępniać? trzeba pomyśleć.. i szybko to zrobić. 
btw. trzeba będzie zweryfikować czy nie wykorzystać transakcji lub dodać elementy przeciwdziałające wysypywaniu się naszych formularzy gdy jednocześnie będzie ktoś chciał edytować formularze i dodawać instancje itd.. na pewno w tej chwili mogą wystąpić z tym problemy.

**Comment by ofilipowicz** [comment]
Zabieram się za to.

**Comment by marcin-pwr** [comment]
to super, tam na fb coś na ten temat też skrobnąłem, btw. może znajdzie się jakaś gotowa apka do udostępniania treści albo jakieś rozszerzenie do allautha, hm, zresztą wiesz najlepiej jak to ogarnąć..
