### ISSUE TITLE
Wyszukiwanie formularzy i projektów

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#30]
- [x] Wyszukiwanie projektów
- [x] Wyszukiwanie formularzy

**Comment by marcin-pwr** [comment]
Czyli zrobić backend dla tych formularzy z szablonów. Tylko gdzie wynik szukania? W miejscu listy projektów, formularzy? Czy jakaś dedykowana stronka z dodatkowymi opcjami? Bo takie filtrowanie np po nazwach to raczej dynamicznie by się przez ajaxa wysyłało i podmieniało ten kontener z listą? Chyba byłoby ok..

**Comment by marcin-pwr** [comment]
w zasadzie działa, trzeba będzie rozbudować bo tak po samej nazwie to trochę mało, ale - jak ktoś będzie miał dużo formularzy... na razie zamykam bo szukanie projektów i formularzy działa. będzie trzeba dodać szukanie instancji, tylko najpierw warto przebudować listę instancji bo te daty wstawień trochę lipnie tam się prezentują..
