### ISSUE TITLE
Usuwanie modelu Image z bazy danych

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#33]
Exception Type: FileNotFoundError
Exception Value: [Errno 2] No such file or directory: 'D:\\GitHub\\owndb\\images\\australia_3.jpg'
Exception Location:	C:\Python34\lib\site-packages\django\core\files\storage.py in _open, line 172

edycja formularza już działa, z wyjątkiem formularzy w których istnieją labele zdjęciowe, gdyż podczas usuwania obiektu Image z bazy występuje powyższy błąd. 

Dodatkowe info o problemie:
- po wywołaniu metody .delete() na wybranym modelu Image plik jest usuwany poprawnie z systemu plików, natomiast jest dalej widoczny rekord w bazie danych
- być może django próbuje z jakiegoś powodu dwukrotnie usunąć ten sam plik, no i nie usuwa rekordu z bazy, 

Testowałeś Oskar czy to usuwanie działa? nawet w statycznym widoku jak się wyszuka po konkretnym pk który image jest w bzie i w folderze ze zdjęciami to usuwa plik z folderu, nie usuwa rekordu z bazy i wyświetla błąd na stronie. hmmm... pomysł?

**Comment by marcin-pwr** [comment]
PermissionError at /admin/store/image/7/delete/
[WinError 32] Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany pr...
---w panelu admina też wywala błąd i nie chce usunąć, z tym, że tutaj nawet pliku nie usuwa z folderu.

**Comment by ofilipowicz** [comment]
Tego usuwania jeszcze do końca nie testowałem. Jeśli chodzi o PermissionError to wydaje mi się być winą Windowsa. To usuwanie jest zrobione pod Linuxa. Win i Linux trochę inaczej zarządzają uprawnieniami.

**Comment by marcin-pwr** [comment]
Może tą post delete trzeba inaczej zaimplementować? może jakiejś linijki tam brakuje, nie wiem wywołania jakiejś generycznej metody? no bo ewidentnie usuwanie pliku z folderu działa (tamten drugi error to inna sprawa) natomiast nie usuwa się rekord z bazy danych, hmm? 

2. można w tych metodach modeli odwoływać się do innych modeli w sensie zapytań do bazy?
bo chodzi mi np. o to żeby tak jak mówiliśmy np. w metodzie display modelu gdzie trzymamy dane instancji checkboxa od razu go renderować do czego potrzebne są etykiety elementów z ustawień formfielda? wracając do tego modelu Image, może trzeba tam jakiegoś self delete() wywołać po fizycznym usunięciu pliku? co myślisz?

**Comment by ofilipowicz** [comment]
Właśnie posprawdzałem różne kominacje i przez panel administratora usunięcie obiektu powoduje usunięcie zarówno rekordu w bazie jak i plików z systemu. Nie wyskakują żadne błędy.

**Comment by ofilipowicz** [comment]
Ps. Sprawdź jeszcze raz ustawienie plików statycznych media [URL](https://docs.djangoproject.com/en/1.8/howto/static-files/#serving-files-uploaded-by-a-user-during-development). U mnie w local_settings mam zrobione tak MEDIA_ROOT = '/home/kozbi/Git/owndb/owndb/media/'. Pliki wrzucają się do /home/kozbi/Git/owndb/owndb/media/images, miniaturki do home/kozbi/Git/owndb/owndb/media/CACHE/images/images (ta biblioteka sama dodaje jedno images dlatego tak dziwnie podwójnie to wygląda)

**Comment by marcin-pwr** [comment]
Sprawdzę, ale widzisz mi katalog /media jest pusty a obok mam /images i tam się uploadują zdjęcia, ja w swoim localsettings to mam tylko dane bazy;) a mediaroot z tego głównego.

**Comment by marcin-pwr** [comment]
czytam to co podlinkowałeś, patrzę na nasze owndb urls.py, patrzę na settings.py no i nie ma nigdzie MEDIA_ROOT ani STATIC_ROOT to jak to w końcu ma być, co Ty masz w końcu w tym local_settings?;) hmm pokombinuję jeszcze...

**Comment by ofilipowicz** [comment]
Aktualnie u mnie local_settings.py wygląda tak:

MEDIA_ROOT = '/home/kozbi/Git/owndb/owndb/media/'
STATIC_ROOT = '/home/kozbi/Git/owndb/owdn/static/'
EMAIL_HOST_PASSWORD = '*pass*'


W dniu 28 kwietnia 2015 19:44 użytkownik marcin-pwr <
notifications@github.com> napisał:

**Comment by ofilipowicz** [comment]
Wielka nierozwiązana niewiadoma. Zamykam.
