### ISSUE TITLE
Wyświetlanie szczegółów instancji.

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#36]
JW, nie uwzględnia innych typów niż zdjęcia i tekst, nie ma wyświetlania liczb, i reszty pól. Należy to naprawić żeby nie wyświetlało błędów. W tej chwili nie można otworzyć szczegółów instancji formularzy z innymi polami niż zwykły tekst i zdjęcia. Chociaż jakieś zastępcze teksty tymczasowo wstawić...

**Comment by ofilipowicz** [comment]
#5

**Comment by marcin-pwr** [comment]
ok, zrobiłem, jbc łatwo będzie zesplitować ew te typy do oddzielnych tabel tylko 1 linijka zmiany i przeniesienie części display() do innego modelu... zamykam.
