### ISSUE TITLE
Przemyśleć wyświetlanie pola NextForm

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#37]
Mamy go nie wyświetlać, zatem hmm, przy obecnym filtrze instance, metoda getdata() z formfielda musi zwracać kolekcję żeby to działało, no a w przypadku niektórych pól tu: NextForm , nie ma danych w tabelach datatext ani image ani innych w przyszłości. Nie sprawdza się nawet że lub forminstance jest puste. proponuję dodać jakiś warunek, żeby dopuścić pomijanie wyświetlania pól w forminstance-detail na podstawie typu.  pomysły?

tymczasowo przy dodawaniu instancji zakomentowałem pomijanie tego pola, no ale tak absolutnie nie może zostać. nawet jakbym dał przy dodawaniu formularza na tej zasadzie jak labela textowego to też bez sensu by było. zatem przedostatnie zdanie z poprzedniego akapitu raczej...

**Comment by ofilipowicz** [comment]
Ja NextForm nie robiłbym jako dodatkowe pole tylko jako atrybut formularza (char z urlem). Wtedy przy tworzeniu nowego formularza na samym dole byłby checkbox, czy dodać taki odnośnik czy nie. Jeśli zaznaczone to pojawia się text input na url.

W szablonie po całej kolejce formfieldów sprawdzać czy to pole coś zawiera, jeśli tak to wyświetla się przycisk przekierowujący zamiast przycisku zapisz. Jeśli pole puste to wyświetlany przycisk zapisz.

**Comment by marcin-pwr** [comment]
ciekawa propozycja, tak można zrobić, bo w sumie jeden przycisk wystarczy. jedno przekierownaie starczy bo teraz to jest tak, że jak się wsadzi kilka nextformów do formularza to możemy do różnych przechodzić. ale z tym przeniesieniem tego do formularza powinno być ok. Przy okazji to zrobię.

**Comment by marcin-pwr** [comment]
nieaktualny, zamykam, bo zmieniamy podejście - musimy zrobić oddzielną sferę widoków (lub zagnieździć to w obecnych) dla sekwencji i i ich tworzenia itd itp, przy tworzeniu formularza nie ustalamy sekwencji.,  ..  wyświetlanie jbc jest poprawione. ale musimy pójść w inną stronę,
