### ISSUE TITLE
Problem z iterowaniem instancji

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#38]
Od początku istnieje pewien problem z przechodzeniem pomiędzy kolejnymi instancjami w widoku forminstance-detail. Mianowicie chodzi o to, że gdy dodajemy instancje do formularza, potem dodamy kilka do innego, i znowu do tego poprzedniego to tworzą się takie jakby znane z matematyki dyskretnej "permutacje". Kolejne serie grupują się i można przechodzić przy pomocy tych przycisków strzałek tylko w obrębie tych grup. Czyli cała przestrzeń instancji formularza dzieli się na permutacje w miejscach w których zostanie wstawiona instancja do jakiegoś innego formularza. Gdzieś pewnie zastosowano uproszczenie ciągłości numeracji pk instancji, ciężko powiedzieć ale gdzieś trzeba zrobić jakiś myk żeby to działało, O! w previnstance, nextinstance w tym modelu instancji jest coś nie tak, Oskar zostawiam to Tobie;P..

**Comment by ofilipowicz** [comment]
Racja, o tym nie pomyślałem. Zajmę się tym.
