### ISSUE TITLE
Testy aplikacji

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#39]
Należy rozpocząć tworzenie testów dla aplikacji, bo się rozbudowuje i zaczyna się ciężko sprawdzać czy przy wprowadzaniu zmian nie psuje się innych części aplikacji. Potrzebni są "ochotnicy" do zajrzenia w tutorialu jak się robi testy i wzięcia się za to.. nie jest to trudna rzecz, chyba raczej schematyczna jak już się zacznie..

**Comment by ofilipowicz** [comment]
Popieram, testy sporo ułatwiają życie.

**Comment by ofilipowicz** [comment]
Testy tylko akceptacyjno-klikalne. Zamykam.
