### ISSUE TITLE
Autoryzacja użytkowników

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#4]
- [x] Logowanie
- [x] Rejestracja
- [x] Aktywacja e-mailem
- [x] Integracja z zewnętrznymi serwisami (Facebook, Twitter, Google)
- [x] Autoryzacja dla widoków
- [x] Uprawnienia

**Comment by marcin-pwr** [comment]
What if someone insert bad data in login inputs? Some infos will be fine, or redirection to login page maybe.
