### ISSUE TITLE
Przebudowa widoku listy instancji...

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#42]
jw, co myślicie. Jak dla mnie to te daty kiedy ktoś wstawił jaką instancję nie są zbyt atrakcyjne, szczególnie tuż na wejściu do formularza.. hm, ...

**Comment by ofilipowicz** [comment]
Tak jak było powiedziane, trzeba wyświetlać wszystkie filedy z danego formularza jako kolumny. Zdjęcia prezentowane w formie miniatur.

**Comment by marcin-pwr** [comment]
wstępnie zrobione, ale trzeba poprawić żeby źródłem zdjęć były miniatury zamiast oryginałów. no i zdecydować jak wyświetlać labele (czy w ogóle jak są te osobne nagłówki pól), jak połączenia, a jak pliki.

**Comment by ofilipowicz** [comment]
Jeśli nadal nie działają te miniaturki to można je spróbować generować automatycznie. Tak jak jest to [tutaj](https://github.com/matthewwithanm/django-imagekit#generateimage) opisane.

**Comment by marcin-pwr** [comment]
ale on by je CACHE'ował? .. wiesz, jest to w masterze jbc, u mnie działa tak jak widziałeś, ale może na linuxie będzie ok. na pewno ten dodatkowy display może się przydać bo będzie można w ten sposób customizować wyświetlanie poszczególnych typów na listach i w szczegółach..

**Comment by marcin-pwr** [comment]
zamykam bo jest w miarę ok, są kolumny z danymi itd. , jak coś ktoś wymyśli to może poprawić.
