### ISSUE TITLE
Sekwencje, przepływ formularzy

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#44]
Dodać osobną funkcjonalność, która globalnie dla całego projektu pozwala określić różne viewflowy (viewflowy mogą być udostępniane, ale widoczne są w charakterze kreatorów. Przy tworzeniu viewflowa określa się które i w jakiej kolejności formularze mają się pojawiać po zatwierdzaniu poszczególnych ekranów. Ma być możliwość tworzenia rozgałęzień tak jak to jest w tej chwili. Ale wszystko ma być ustawiane globalnie na oddzielnym widoku. Należy dodać oddzielny model, gdyż pojedynczy formularz może być w kilku viewflowach, zatem w modelu formularza tego nie trzymamy.

**Comment by ofilipowicz** [comment]
Nie wiem w sumie czy to robić. Mamy już w sumie działający mechanizm przepływu (w postaci fielda. Może jutro się za to zabiorę.
