### ISSUE TITLE
Filtracja adresów URL

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#45]
Trzeba zabronić wyświetlania instancji przez podmianę adresu URL. Teraz jest tak, że jak sobie wyświetlamy instancje z danego formularza, to jak w pasku adresu zmienimy numerek na inny to nam się wyświetli jakaś instancja nawet z innego projektu. Nie byłby to wielki problem jeżeli byłby jeden użytkownik, ale jak mamy kilku to możemy szperać w kogoś formularzach. Trzeba koniecznie to zablokować. Osobiście poszedłbym w stronę jakichś filtrów, dekoratorów i stworzył globalny mechanizm, który sprawdzałby czy dany użytkownik ma dostęp do widoku dla podanych parametrów z URL'a. Ale może Oskar masz jakiś sprytniejszy pomysł jak to da się systemowo rozwiązać?

**Comment by ofilipowicz** [comment]
W szablonach warunek sprawdzający uprawnienia danego użytkownika. Przy braku wyświetli stosowny komunikat. Zajmę się tym.

**Comment by marcin-pwr** [comment]
ok, najbardziej elastycznie.....no na pewno fragmenty interfejsu w zależności od uprawnień/udostępnień formularzy itd muszą być ukrywane itp, natomiast hmm, no jak uważasz tylko jak ktoś nie ma dostępu do danego adresu to można by wyświetlić jakąś stronę błędu nawet, chodzi mi może bardziej o to, że w takim szablonie za dużej logiki się nie zmieści , wiesz jakieś ew przekierowania itd.. np jak wprowadzi się zły numer instancji to przekierowanie do listy instancji, zły numer formularza-do ich listy itd. takie poprawki podstawowe,no bo na pewno nie należy robić np.  że jak użytkownik poda zły numer to go przekieruje do najbliższego możliwego dopasowania, ale te co wcześniej napisałem no można. zresztą no ok, zrób tak jak masz pomysł , byle żeby zabezpieczyć te elementy bo to raczej ważna sprawa;-)

**Comment by ofilipowicz** [comment]
Zrobione.
