### ISSUE TITLE
Dodać mechanizm zabezpieczający przy rejestracji konta

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#47]
jw, może reCAPTCH'ę od Google'a?

**Comment by ofilipowicz** [comment]
@nosstek Jak postęp?

**Comment by marcin-pwr** [comment]
Zajebisty feedback.

**Comment by nosstek** [comment]
Przepraszam za brak feedbacku.
Rozwiązanie z reCAPTCHA. Nie wyświetla mi się poprawnie, chciałem to
poprawić i pokazać tydzień temu. Mam nadzieje, ze jutro mi się uda.

2015-06-05 13:33 GMT+02:00 marcin-pwr <notifications@github.com>:
