### ISSUE TITLE
Model pól wyboru i wyświetlanie 

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#5]
Chcemy, żeby użytkownik mógł posiadać w swoich formularzach pola wyboru (radio i check box)

**Comment by marcin-pwr** [comment]
Yes. I think about it. We should rather store it as string and parse it, I work in that's way. possibl1;;posibl2;;...;;posibln in field model and 1;0;1;0;..;1 in associated data model. if radio then data could be as number 0,1,.n this determine which option was selected. Better solutions very welcome.

**Comment by marcin-pwr** [comment]
Trzeba przygotować metodę display(), która by na podstawie ustawień z modelu FormField odpowiednio to renderowała. I tu faktycznie przydałby się oddzielny  model np. DataChoice, DataCheckbox zamiast trzymania wszystkiego w DataText.

**Comment by ofilipowicz** [comment]
Napiszę tę metodę tylko faktycznie wygodniej byłoby trzymać te dane w oddzielnej tabeli.

**Comment by ofilipowicz** [comment]
Przepiszesz ten kreator formularza, żeby dla każdego typu była oddzielna tabela? Wtedy będę mógł zrobić poprawne wyświetlanie instancji.

**Comment by marcin-pwr** [comment]
żeby podpiąć nowe modele jbc wystarczy w widokach dodać warunek i zapisywać dany typ do innego.. wyświetlanie choice'a i checkbox'a działa, są te co się wybrało, trzeba to ew graficznie poprawić ale logicznie działa. później usunę tę pierwszą liczbę w settingsach bo jej się nie używa widzę tylko iteruje po tablicy, a wymaga dodatkowego kodu do pomijania... ok. zamykam.
