### ISSUE TITLE
Naprawić rejestrację

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#50]
Za nic nie da rady zarejestrować nowego użytkownika. Najpierw próbowałem normalnie przez formularz, wypełniam pola i żadnej informacji o czymkolwiek, no nic na poczcie nic nie przyszło. Wchodzę do admina i tworzę nowego użytkownika, loguję się jest prośba o potwierdzenie emailem, ustawiam w formularzu adres email, loguję jeszcze raz nic nie przychodzi na pocztę. Dodaję ręcznie email przez admina, wyskakuje błąd:
IntegrityError at /store/
BŁĄD:  podwójna wartość klucza narusza ograniczenie unikalności "account_emailaddress_email_key"
DETAIL:  Klucz (email)=(***@gmail.com) już istnieje.
Chciałbym potestować udostępnianie;-)

**Comment by ofilipowicz** [comment]
Próbuj przez formularz. Na 90% coś źle podajesz, ale nie widzisz alertow z
walidacji. Mnie się w końcu udało. Jak nie masz cierpliwości to zainstaluj
crispy_forms i z nim wygeneruj formularz. Będziesz miał tam alerty.

**Comment by marcin-pwr** [comment]
dodałem ten form|crispy  zamiast tamtych pól i wszystko jasne;) hasło było za krótkie., no a ja cały czas admin admin, adminek przeszło, ok, zamykam. ale weźcie dodajcie te crispy forms do mastera i fajnie jakby te informacje jakoś bardziej estetycznie może jakieś dymki albo coś-ale rzecz gustu
.. o już chciałem pisać w nawiązaniu do poprzedniego błedu, a tu proszę teraz jest nawet alert że email ma już jakiś użytkownik. ok. fajnie.
