### ISSUE TITLE
Drobne poprawki i uwagi

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#51]
1. przy dodawaniu frienda jeżeli podamy złą nazwę użytkownika to wyrzuca błąd (omessageować;)
2. dodać krótkie info jak dodajemy friendów (w sensie że to ma być nazwa usera);)
3. dodać usuwanie friendów
4. podczas wyświetlania tego bootboxa następuje przesunięcie belki menu w prawo z powodu zniknięcia paska przewijania w Chrome (minimalnie drażni;)
5. czy dodanie frienda należy potwierdzać?
6. po dodaniu frienda automatycznie pojawia się na liście drugiego usera.
7. nie mogę udostępnić innemu użytkownikowi, na liście friendów mam innego usera, natomiast na liście w share form jest tylko nazwa aktualnie zalogowanego,.. mogę coś robić nie tak? jakaś procedura specjalistyczna;)

**Comment by marcin-pwr** [comment]
ad4. https://github.com/twbs/bootstrap/issues/14040 - poprawione

**Comment by ofilipowicz** [comment]
ad 5. Aktualnie zrobione jest tak, że po dodaniu friendsa od dodawana jest znajomość. Nikt nie musi nic potwierdzać. Oczywiście wszystko jest przygotowane żeby requesty działały, ale trzeba byłoby to zaimplementować - "jak starczy czasu".

ad 6. Patrz wyżej.

ad 7. Racja. To, że działało mi wcześniej to musiała być kwestia przypadku. Udało mi się to już naprawić, wieczorem zmerguje do mastera.

**Comment by ofilipowicz** [comment]
Chyba wszystko już zrobione i działa.
