### ISSUE TITLE
Translacje

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#53]
jw jak progress? Działa już ta zmiana języka?

**Comment by marcin-pwr** [comment]
Dodałem translacje, weźcie jak możecie puśćcie na linuxie te makemessages bo u mnie zanim rozwiążę problem z gettextem trochę minie;) ale mechanizm działa, doróbcie pliki *.po i tłumaczcie apkę. Postarajcie się też dodać wszędzie te transy.

**Comment by marcin-pwr** [comment]
tzn. robi to Łukasz i Tomasz, jak będziecie mieli już trochę tego to wrzucajcie na gita, żeby było widać  czego brakuje.

**Comment by marcin-pwr** [comment]
trzeba przerobić translacje w tych account aby w kodzie było po angielsku a nie po polsku bo zauważcie że w pliku translacji na polski mamy polskie źródłowe stringi! na co mamy je tłumaczyć na angielski? w polskim pliku lokalizacji? no jak.

**Comment by marcin-pwr** [comment]
Aha @nosstek  jak tam translacje store? mógłbyś wrzucać na nowego brancha co jakiś czas co już zrobisz? nie musisz czekać do momentu aż skończysz, będzie pogląd co jest zrobione a co nie jw.

**Comment by LukeSagittarius** [comment]
BTW czemu branch i7 został usunięty? Commitować na mastera?

**Comment by marcin-pwr** [comment]
Nie na mastera nie commituj bo się zrobi bałagan. Weź spushuj na jakiegoś brancha nazwij go jak chcesz, najlepiej i53 .

**Comment by marcin-pwr** [comment]
Nie odpalajcie makemessages! Bo się taki bałagan robi przy mergowaniu że ta osoba sama to będzie ogarniać lub po prostu commit zostanie cofnięty. Robicie albo transy w szablonach albo tłumaczycie stringi na najnowszym masterze jak zaczynacie tłumaczyć piszcie tutaj że to robicie i od razu na koniec pushujcie.

**Comment by marcin-pwr** [comment]
Ogarnąłem wszystko, jest dobrze, działa. Zamykam, znajdziecie braki w tłumaczeniach to patrzcie opis commita: https://github.com/ofilipowicz/owndb/commit/d9350dad465368194d90b7a71186797c1d73292c
