### ISSUE TITLE
Poprawić strony statyczne

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#54]
Poprawić poniższe strony.

- [x] Home - musi wyglądać inaczej - prościej, krócej i nie tak jak Google Forms :smiling_imp:
- [x] Contact - jakiś sensowny kontent
- [x] Help - chce się komuś pisać jakieś proste instrukcje naszego systemu? Jak obsługiwać formularze, udostępnianie, connections itd.
- [x] About us - trochę o nas. Projekt z PWR itd.

@c00perpl @LukeSagittarius Podzielcie się robotą.

**Comment by c00perpl** [comment]
Sam to wszystko zrobię. Niech Łukasz z Tomkiem robią tłumaczenia. Jak zrobię wszystko wrzucę na i1 i pull request.
