### ISSUE TITLE
Poprawić navbar - flagi, logowanie

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#55]
- [x] Logowanie jako link do strony logowania, bez formularza w navbarze. 
- [x] Zamiast listy języków dwie, małe flagi na prawym krańcu navbaru.
- [x] Oddzielić Owndb (z lewej strony) od nawigacji. Np. pionową kreską. Następnie każda podstrona po jakimś znaczku przejścia. Przykładowo: Owndb | My projects > My forms > Form instance

**Comment by marcin-pwr** [comment]
hola hola;D te znaczki przejścia nie w ten sposób! żeby wprowadzić takie coś to nie wystarczy tam dodać te > bo potem w wersji mobilnej wygląda to paskudnie. zresztą w takiej zwykłej też, widzicie że tam elementy są jako lista ul i li mają odstępy bootstrapowe, no kicz na maksa jeżeli tak Kamil wszystkie szablony chcesz przelecieć i dorzucić ">" - proszę się wstrzymaj ;)

**Comment by ofilipowicz** [comment]
Nom. Lepiej ostylować w CSS elementy <li>

**Comment by s200894** [comment]
Zrobiłem jak umiałem te znaczki, proszę się nie czepiać ;) Flagi zrobiłem już tylko dałem class="btn btn-default", trzeba by tam zmienić tło i dać border: none.

**Comment by marcin-pwr** [comment]
ok, ale najpierw spulluj mastera (bo defacto są tam już te flagi;) i pomyśl co można jeszcze ulepszyć w różnych miejscach, weź też sprawdź czy dalej wystąpi ten błąd co wtedy i spróbuj teraz zrobić te scenariusze. Czy te flagi powinny być całkiem z prawej nie wiem, przycisk wylogowania dobrze tam pasuje bo zazwyczaj tam właśnie lecimy kursorem i flagi mogłyby być zbyt mocno akcentowane.

**Comment by s200894** [comment]
Ale flagi te co ja zrobiłem to działają a te z mastera to coś niebardzo. Flagi moim zdaniem są w dobrym miejscu.

**Comment by marcin-pwr** [comment]
no jak nie działają;)?

**Comment by s200894** [comment]
Aa dobra, działają, ja patrzyłem na adres bo wczesniej w adresie było pl lub eng a teraz widzę że tego nie ma

**Comment by marcin-pwr** [comment]
heh wiem, chodzi o to że teraz przekierowuje do tej samej strony tzn. nie przekierowuje do strony startowej (to na plus) natomiast tak, na bieżącej stronie znika pl/ en/ z adresu, ale to chyba nie jest duży problem.
