### ISSUE TITLE
Weryfikacja dodania instancji, edycja dodanych instancji i ich wyszukiwanie

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#57]
Instancja dodaje się cała albo w ogóle (błąd).

**Comment by marcin-pwr** [comment]
Dorzucam do tego edycję tych instancji i ich wyszukiwanie.

**Comment by marcin-pwr** [comment]
ok, przy okazji w ramach konserwacji ulepszę jeszcze kod widoków, edycja instancji już działa, wyszukiwanie na razie po dacie dodania ale pole jest obsłużone zatem można tam w widoku dodać kilka zapytań żeby szukało kaskadowo w głąb instancji formularza. zmaykam.
