### ISSUE TITLE
Dokumentacja i manual

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#61]
Gdzieś tam Sebastian rzuciło mi się w oczy zdanie, że nazwa pola nie może zawierać spacji i służy do identyfikacji pola w systemie. Nie, nic bardziej mylnego! Nazwa pola to ma być przyjazna nazwa i jest ona wyświetlana jako nagłówek kolumn, czy to w okienku wyboru instancji w połączeniu czy to na liście instancji formularza, jak również przy ustawianiu widoczności poszczególnych kolumn. Dobrze, żeby nie było tam pół strony tekstu, ale bez przesady. Zatem proszę to poprawić wszędzie w dokumentacji. Przy okazji myślę, że trzeba będzie ją przejrzeć bo osoby które implementują najwięcej wiedzą jak to działa i jakie dokładnie są możliwości i ograniczenia. Ale tak trzymaj, postaraj się ją dokończyć.

**Comment by 200907** [comment]
Ok, uwzględnię to przy najbliższym wydaniu - po prostu we wcześniejszej wersji systemu nie działało mi ze spacjami, po zaktualizowaniu jest już dobrze. 
Niemniej to, o czym piszesz, to jak by nie patrzeć - identyfikacja pól formularza po nazwie.
