### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by marcin-pwr** [ofilipowicz/owndb#62]
Jak najlepiej to zrobić? Może Apache'a jako serwer ze wsparciem dla Pythona, a nginx dla plików statycznych i mediów? Trzeba WSGI ogarnąć itp. Ktoś się tym zajmuje? @nosstek coś robiłeś no nie, ale przydałoby się to gdzieś opisać w dokumentacji jbc. Aha, no i najważniejsze czy działało Ci w wersji produkcyjnej czy już docelowej? Zmieniałeś DEBUG w pliku ustawień? I czy działały pliki statyczne i upload?

**Comment by nosstek** [comment]
Dodaje jeszcze Apache'a. Dokumentacje do tego i do nginxa spisze do
osobnego pliku bo i tak już jest za późna pora. Zjebałem - nie ogarniałem
tych maili. Lądowały mi w spamie.
Jest też postawiony serwer mail żeby nie wysyłać z gmaila maili
rejestracyjnych. Pewnie nie uda mi się już żeby to działało docelowo, nie
zmieniałem też opcji debugowych - normalnie leciały.
Już pokaże jutro na zajęciach jak uda mi sie cokolwiek.
Pzdr.

W dniu 4 czerwca 2015 22:44 użytkownik marcin-pwr <notifications@github.com>
napisał:
