### ISSUE TITLE
Błędy w tłumaczeniu

### ISSUE THREAD

**Issue by s200894** [ofilipowicz/owndb#64]
Wypisujmy tutaj znalezione błędy w tłumaczeniu i nieprzetłumaczone jeszcze fragmenty.

"Jeżeli jeszcze nie utworzyłeś konta, proszę zarejestruj się najpierw." jakoś to brzmi tak google translate z tym najpierw na końcu

przy tworzeniu formularza:
"Choose type:"
"Remove or customize this field."

Przy wybieraniu połączonego formularza :
"Choose one instance from connected form."

**Comment by marcin-pwr** [comment]
Dobry pomysł z issue;)
1. poprawione,
2. poprawione częściowo(tylko przy edycji istniejących pól formularza)
3. poprawione
4...kilka dodatkowych.

ad2. nie wystarczy dodać transa bo stringi są w skrypcie js. zatem albo się wyodrębni stringi i gdzieś w atrybutach lub w ukrytych polach będzie trzymać w szablonie albo kod skryptu wklei się np. do base'a i tam będzie można wtedy go do woli tłumaczyć;)

**Comment by s200894** [comment]
Kolejna dostawa niedopatrzeń:
Brakuje regulaminu przy rejestracji, trzeba dopisać chociaż cokolwiek.
Nieprzetłumaczony przycisk "Sign up".

Przy wyszukiwaniu formularzy komunikat:
"List of forms with "Filie" term. "

Wysyłanie wiadomości, myślę że bardziej by pasowało "wyślij" niż "zgłoś" ;D

Poza tym już wszystko gitnie :)

**Comment by marcin-pwr** [comment]
Spulluj najnowszego mastera i weź przygotuj już tak na gotowo te przypadki użycia żeby można było zaprezentować wszystko co udało się zrobić.

**Comment by s200894** [comment]
Dobra, jeszcze tylko mi powiedz czemu mi nie działa rejestracja nowego użytkownika ? 
![screen9](https://cloud.githubusercontent.com/assets/11329148/8114140/c8461eb4-1072-11e5-9306-753562830226.png)

**Comment by marcin-pwr** [comment]
Przetestowałem przed chwilą i mi działa wszystko ładnie, oprócz kliku literówek w tłumaczeniach tamtych stron accounts'a. Co to jest to webmaster@localhost? Na pewno masz w local_settings dane gmaila? jbc to pytaj @ofilipowicz o szczegóły;)

**Comment by ofilipowicz** [comment]
Musisz mieć hasło do konta Gmail w local_settings. Opisywałem to gdzieś na
Facebooku.
