### ISSUE TITLE
Widoki dodawania i edycji projektów

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#8]
- [x] project-edit
- [x] project-add

**Comment by marcin-pwr** [comment]
Propably, they will be lightweight.

**Comment by ofilipowicz** [comment]
project-edit musi mieć jeszcze opcje usuwania projektu, wraz z ostrzeżeniem, że wszystkie formularze i dane w nim zawarte zostaną utracone.

**Comment by marcin-pwr** [comment]
Kamil mógłby to zrobić w tym branchu gdzie jest usuwanie formularza. Ale jednak chyba wypadałoby dodać jeszcze jeden pośredni widok z tym potwierdzeniem usunięcia, czyli w szablonie project-edit byłby oddzielny formularz do usuwania np. Albo dodać radio boxa którego trzeba zaznaczyć by usunąć projekt.

**Comment by marcin-pwr** [comment]
dodane
