### ISSUE TITLE
Widoki dodawania i edycji formularzy

### ISSUE THREAD

**Issue by ofilipowicz** [ofilipowicz/owndb#9]
- [x] form-add
- [ ] form-edit

**Comment by marcin-pwr** [comment]
Yeah, here it is, I read from the #1 issue;p I'll think how to add them in right place. At first it's hard to catch where to cut these regular expressions and how to prepare appropriate view. I've to read more about it or wait until someone else will insert other static page between project and form ids;)

**Comment by ofilipowicz** [comment]
form-edit musi umożliwiać usuwanie formularza, z ostrzeżeniem, że wszelkie dane zostaną utracone.

**Comment by marcin-pwr** [comment]
Tak, zrobię to w piątek na zajęciach. Tylko musimy przemyśleć czy dopuszczamy edycję formularza jeżeli już zaczęto wprowadzać dane. Jeżeli nie dopuszczamy to byłby okrojony widok edycji tylko z możliwością usunięcia bez modyfikacji jeżeli są dane.

**Comment by s200894** [comment]
Dodałem usuwanie formularzy i wrzuciłem na i9. Nad szablonem form-delete jeszcze trzeba będzie popracować ;p

**Comment by ofilipowicz** [comment]
Jest prawie okej. Jedna rzecz mi tylko nie pasuje. Kiedy wchodzimy w edycji i naciśniemy Delete form, to pojawia się to okno o tych niezapisanych zmianach. Dodatkowoo na pytanie Czy chcemy usunąć formularz możemy odpowiedzieć tylko TAK, nie ma przycisku cofnij czy coś w tym stylu, który powinien nas kierować albo do edycji albo do listy formularzy.

**Comment by marcin-pwr** [comment]
To jedna ważna linijka dodam ją w następnym commicie.
